version: "3"
services:
  web:
    build:
      context: build
    container_name: web1
    restart: always
    networks:
      - traefik_proxy
    labels:
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.rule=Host:web1.flex-guse.de"
    volumes:
      - ./html:/usr/share/nginx/html
networks:
  traefik_proxy:
    external: true